### ISSUE TITLE
How use Foreign keys?

### ISSUE THREAD

**Issue by felipeska** [casidiablo/persistence#9]
https://www.sqlite.org/foreignkeys.html

**Comment by casidiablo** [comment]
There's no built-in implementation for foreign keys... and adding them would take more time that I actually can invest. PRs welcomed :P

**Comment by felipeska** [comment]
btw, is there anyway to make direct sql statements `db.execSQL` ?

**Comment by casidiablo** [comment]
Yes... https://github.com/casidiablo/persistence/blob/master/src/main/java/com/codeslap/persistence/RawQuery.java

**Comment by razorblade446** [comment]
It's Persistence still alive as "Persistence" or "Hongo"? (could  be sweet to be PR)

**Comment by casidiablo** [comment]
It's "persistence"
